name: Release
run-name: ${{ github.actor }} is releasing a new version 🚀
on:
  pull_request:
    paths-ignore:
      - 'example/**'
  push:
    branches:
      - master
    paths:
      - 'src/**'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🧲
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile
      - name: Lint 🧹
        run: yarn lint
      - name: Build 🪛
        run: yarn build
      - name: Release 🪄🎁
        if: ${{ github.ref == 'refs/heads/master' }}
        run: yarn semantic-release
